### ISSUE TITLE
Add GitHub Topics support

### ISSUE THREAD

**Issue by jfredrickson5** [GSA/codeinventory-github#5]
https://github.com/blog/2309-introducing-topics

This can be used to automatically build the tags list for each project.

**Comment by jfredrickson5** [comment]
Topics not yet available via the API, but it seems that GitHub intends to add them in the future.

**Comment by jbjonesjr** [comment]
https://github.com/presidential-innovation-fellows/code-gov-web/issues/225#issuecomment-288205034

**Comment by jfredrickson5** [comment]
Added to the latest release. Thanks for the heads up @jbjonesjr!
