### ISSUE TITLE
Add `code-gov` repo topic

### ISSUE THREAD

**Issue by jbjonesjr** [GSA/codeinventory-github#7]
It would be awesome if this repo could include a `code-gov` topic to make it easily discoverable along other code.gov related utilities on GitHub.com [here](https://github.com/topics/code-gov).

Topics are now an even more prominent part of the discovery experience of GitHub.com (https://github.com/topics), and are being used to help users discover projects they may be interested in (https://github.com/updates). Creating a centralized place for code.gov repositories may also help in reducing duplication of effort as well.

Also, that would then make them more easily searchable on https://code.gov... how meta.

**Comment by jfredrickson5** [comment]
Added!
